; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = https://github.com/Jason2866/platform-espressif32/releases/download/2022.12.2/platform-espressif32.zip
board = nodemcu-32s
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.19.4
monitor_speed = 115200
build_flags = 
	-std=gnu++17
build_unflags = 
	-std=gnu++11

; Tell platformIO to use a partition scheme that gives more space to the program code (default 1.3MB, now we get 3MB)
; Adding BLE was pushing us very close to the 1.3MB default
; This change will stop us from being able to do OTA updates though because the chip won't have enough space to download new firmware
board_build.partitions = huge_app.csv